title:             Techysoul.com
email:             madhav@mindhe.com
description:       Simplifying IT!
author:            Madhav Mindhe
baseurl:           ""
url:               "http://www.techysoul.com"

# Social Profiles
twitter_username:  techysoul
github_username:   techysoul
facebook_username: mindhe

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
